= AsciiDoc notes

== Putting the AsciiDoc source onto the web site

* Change the Last Updated date in the ascii source file
. In AsciiDocFX, Output the HTML file as index.html, replacing the existing one (Click HTML at top of right pane)
. Put the code snippets in GoogleTagManagerSnippets.txt just inside the head and body sections. (includes icon code) using notepad++
. check in the ALA (AsciiDoc) project (to Github) by right clicking on the folder and selecting "Commit to Master"
. Tick any new images
. Note that the web site only uses the file index.html, the images in the \images folder, and the documents in the linkedDocuments folder. All other files being checked in are source files.
. Wait for the website to be "published" takes a minute or so?
. Check the website and its images
. Dont let images have capital letters in the extension - they wont be shown in the web site


=== redundant 
. Log into InmotionHosting.com AMP  johnspray74@gmail.com fw2017
. (CPanel directly (case sensitive name) quicks34 fw2017)
. Go to cPanel, then File Manager
. Browse to public_html\abstractionlayeredarchitecture.com
. Upload any new images from the images folder in the project to the images folder under public_html\abstractionlayeredarchitecture.com
. Rename index.html to index-backup.html be deleted later
. Upload new index.html




== Starting Asciidoc

AsciiDocFX is run from the taskbar, then use the recent side-tab or double click on a .adoc file. Or or double click on a .adoc file


== Using AsciiDocFX


=== Diagrams




== Installation notes

AsciiDocFX was installed using:
"C:\Users\John\Downloads\AsciidocFX_Windows.exe"

=== Graphviz installation

On my desktop machin I had to separately install graphviz, as per the instructions in the AsciiDocFX documentation at asciidocfx.com, from www.graphviz.org, an .msi file. After the install, AsciiDocFX still could not find it. I had to set an environment variable:

 Click Start, right click Computer, Properties, Advanced System Settings, Environment variables. Set GRAPHVIZ_DOT to C:\Program Files (x86)\Graphviz2.38\bin\dot.exe


=== Syntax highlighting?

Installed chocolatey using instruction on the web.
Installed python using instructions 


=== Modification to the css files

I modified the css file used by asciidocfx to improve the headings weight and colour.
Also I fixed the code blocks not showing up with a background highlight.

For some reason this required changing three copies of css files:


"C:\Program Files\AsciidocFX\conf\public\css\asciidoctor.css"

"C:\Program Files\AsciidocFX\conf\public\css\asciidoctor-default.css"

"C:\Users\John\.AsciidocFX-1.7.3\css\asciidoctor-default.css"


For headings weight and colour:

from
h1,h2,h3,#toctitle,.sidebarblock>.content>.title,h4,h5,h6{font-family:"Open Sans","DejaVu Sans",sans-serif;font-weight:300;font-style:normal;color:#ba3925;text-rendering:optimizeLegibility;margin-top:1em;margin-bottom:.5em;line-height:1.0125em}
h1 small,h2 small,h3 small,#toctitle small,.sidebarblock>.content>.title small,h4 small,h5 small,h6 small{font-size:60%;color:#e99b8f;line-height:0}

to

h1,h2,h3,#toctitle,.sidebarblock>.content>.title,h4,h5,h6{font-family:"Open Sans","DejaVu Sans",sans-serif;font-weight:600;font-style:normal;color:#ba3925;text-rendering:optimizeLegibility;margin-top:1em;margin-bottom:.5em;line-height:1.0125em}
h1 small,h2 small,h3 small,#toctitle small,.sidebarblock>.content>.title small,h4 small,h5 small,h6 small{font-size:60%;color:#914f0f;line-height:0}

i.e change font-weight from 300 to 600
change color from #e99b8f to #914f0f 


For code block colour:

from
.literalblock pre,.listingblock>.content>pre:not(.highlight),.listingblock>.content>pre[class="highlight"],.listingblock>.content>pre[class^="highlight "]{background:#f7f7f8}
to
.literalblock pre,.listingblock>.content>pre:not(.highlight),.listingblock>.content>pre[class~="highlight"]{background:#fefced}

i.e. remove ,.listingblock>.content>pre[class^="highlight "]
add ~
change background from #f7f7f8 to #fefced
 
Note: modifyling the above three didn't work at first for my new windows install. I had to get rid of a copy in here, but not sure of that is what realyy made it start working.

"C:\John\Projects\ALA\ALA (AsciiDoc)\styles"

== Old / redundant

=== Generating HTML output

This method was to avoid a bug with auto-generated image names for graphics files not being local relative paths. This issue was overcome by explicitly specifying names for every graphic (which is doable but a pain) This bug is supposedly fixed in version 2.9 

Command to convert the ALA article for uploading to abstractionlayeredarchitecture.com

. Open a command window
. Go to  C:\john\projects\ala\ALA (AsciiDoc)
. asciidoctor -r asciidoctor-diagram '.\Abstraction Layered Architecture.adoc'


=== graphic image reference bug

AsciidocFX tool is great except when generating the HTML, it puts in localhost references to all the graph .png files


==== new workaround

Make sure you give a filename to every graphic, don't let it allocate them automatically

==== old workaround

Work around is use AsciiDoctor, Asciidoctor-diagram.

Installed ruby and set the path - not sure how.

Then in a windows command window used these commands:

gem install asciidoctor diagram

There were various other things I did according to asciidoctor-diagram instractions on Internet, but not sure if any were necessary except this:

command line in a DOS windows containing the file to be converted

asciidoctor -r asciidoctor-diagram '.\Abstraction Layered Architecture.adoc'



=== AsciiDoctor

There are two main ways to use AsciiDoctor (not AsciiDocFX) (the ruby version) on windows.
1. An all in one app call AsciiDocFX.
2. AsciiDoctor.exe, a command line utility (that needs Ruby installed) that converts .adoc files to HTML.
You would then use another uby utility called Guard which can watch the .adoc file for changes, and run AsciiDoctor each time,
then configuare a browser to live watch the HTML file.

In preparation for the 2nd method, I have installed Ruby, and then using the gem command, installed asciidoctor and guard.
The internet page describes how to set up guard.

Installed this ruby installer which also automatically installs its JRE dependency. 
"C:\Users\John\Downloads\rubyinstaller-2.5.1-2-x64.exe"

Then in the DOS command window you can install ruby programs:
gem install asciidoctor
asciidoctor --version

gem install guard guard-shell

I have successfully used the AsciiDoctor.exe utility in a DOS command window by opening Powershell window in the relevant folder and typeing in
AsciiDoctor Cheatsheet.adoc


Command to convert the ALA article for uploading to abstractionlayeredarchitecture.com
Open a command window
Go to C:\john\projects\ala\ALA (AsciiDoc)
asciidoctor -r asciidoctor-diagram '.\Abstraction Layered Architecture.adoc'

